import { ColumnConfig, ReportType } from "../types";

export const reportColumns: Record<ReportType, ColumnConfig[]> = {
  properties: [
    { key: "date", header: "date", align: "left" },
    { key: "propertyName", header: "Property", align: "left" },
    { key: "totalUnits", header: "Total Units", format: "number", align: "right" },
    { key: "soldUnits", header: "Sold Units", format: "number", align: "right" },
    { key: "availableUnits", header: "Available Units", format: "number", align: "right" },
    { key: "enquiries", header: "Enquiries", format: "number", align: "right" },
  ],
  "users-access": [
    { key: "timestamp", header: "Timestamp", format: "date", align: "left" },
    { key: "name", header: "User Name", align: "left" },
    { key: "role", header: "Role", align: "left" },
    { key: "eventType", header: "Event Type", align: "left" },
    { key: "ip", header: "IP Address", align: "left" },
    { key: "userAgent", header: "User Agent", align: "left" },
  ],
  agents: [
    { key: "date", header: "date", align: "left" },
    { key: "agentName", header: "Agent Name", align: "left" },
    { key: "leadsAdded", header: "Leads Added", format: "number", align: "right" },
    { key: "enquiries", header: "Enquiries", format: "number", align: "right" },
    { key: "siteBookings", header: "Site Bookings", format: "number", align: "right" },
    { key: "leadsClosed", header: "Leads Closed", format: "number", align: "right" },
    { key: "conversionRate", header: "Conversion Rate", format: "percent", align: "right" },
  ],
  "team-leads": [
    { key: "period", header: "Date", format: "date", align: "left" },
    { key: "teamLeadName", header: "Team Lead", align: "left" },
    { key: "teamMembers", header: "Team Members", format: "number", align: "right" },
    { key: "totalLeads", header: "Total Leads", format: "number", align: "right" },
    { key: "leadsClosed", header: "Leads Closed", format: "number", align: "right" },
    { key: "conversionRate", header: "Conversion", format: "percent", align: "right" },
    { key: "totalSales", header: "Total Sales", format: "currency", align: "right" },
  ],
  "sales-managers": [
    { key: "date", header: "Date", format: "date", align: "left" },
    { key: "managerName", header: "Manager Name", align: "left" },
    { key: "customerName", header: "Customer", align: "left" },
    { key: "projectName", header: "Project", align: "left" },
    { key: "unitType", header: "Unit Type", align: "left" },
    { key: "unitNo", header: "Unit No", align: "left" },
    { key: "revenue", header: "Revenue", format: "currency", align: "right" },
  ],
  contractors: [
    { key: "period", header: "date", align: "left" },
    { key: "contractorName", header: "Contractor", align: "left" },
    { key: "tasksCreated", header: "Tasks Created", format: "number", align: "right" },
    { key: "tasksApproved", header: "Tasks Approved", format: "number", align: "right" },
    { key: "tasksRejected", header: "Tasks Rejected", format: "number", align: "right" },
    { key: "invoicesCreated", header: "Invoices", format: "number", align: "right" },
    { key: "photoEvidenceCount", header: "Photo Evidence", format: "number", align: "right" },
    { key: "avgProgressPercent", header: "Avg Progress", format: "percent", align: "right" },
  ],
  "site-incharge": [
    { key: "period", header: "date", align: "left" },
    { key: "name", header: "Site In-Charge", align: "left" },
    { key: "projectsActive", header: "Active Projects", format: "number", align: "right" },
    { key: "qcTasksCreated", header: "QC Tasks", format: "number", align: "right" },
    { key: "tasksVerified", header: "Tasks Verified", format: "number", align: "right" },
    { key: "inspections", header: "Inspections", format: "number", align: "right" },
    { key: "avgProgressPercent", header: "Avg Progress", format: "percent", align: "right" },
  ],
  accounting: [
    { key: "period", header: "Date", align: "left" },

    { key: "accountantName", header: "Accountant", align: "left", },

    { key: "invoicesReceived", header: "Invoices Received", format: "number", align: "right", },
    {
      key: "invoicesApproved",
      header: "Invoices Approved",
      format: "number",
      align: "right",
    },
    {
      key: "invoicesRejected",
      header: "Invoices Rejected",
      format: "number",
      align: "right",
    },
    { key: "invoicesPaid", header: "Invoices Paid", format: "number", align: "right" },
    // {
    //   key: "taxUploads",
    //   header: "Tax Uploads",
    //   format: "number",
    //   align: "right",
    // },
    // {
    //   key: "taxClaims",
    //   header: "Tax Claims",
    //   format: "number",
    //   align: "right",
    // },
    {
      key: "budgetUtilizedPercent",
      header: "Budget Utilized %",
      format: "percent",
      align: "right",
    },
  ],
};
